export { default as DashboardPage } from './DashboardPage'
export { default as ContactsPage } from './ContactsPage'
export { default as CompaniesPage } from './CompaniesPage'
export { default as DealsPage } from './DealsPage'
export { default as TasksPage } from './TasksPage'
export { default as SettingsPage } from './SettingsPage'
